const lessons = [
  {
    id: 111,
    subject: "English",
    location: "Hendon",
    price: 20.5,
    space: 5,
    image: "images/englishLogo.png",
  },
  {
    id: 222,
    subject: "Maths",
    location: "Ealing",
    price: 15.5,
    space: 5,
    image: "images/mathsLogo.png",
  },
  {
    id: 333,
    subject: "Science",
    location: "Hendon",
    price: 10.0,
    space: 5,
    image: "images/scienceLogo.png",
  },
  {
    id: 444,
    subject: "Music",
    location: "Hammersmith",
    price: 10.0,
    space: 5,
    image: "images/musicLogo.png",
  },
  {
    id: 555,
    subject: "Art",
    location: "Ealing",
    price: 10.0,
    space: 5,
    image: "images/artLogo.png",
  },
  {
    id: 666,
    subject: "Geography",
    location: "Acton",
    price: 10.0,
    space: 5,
    image: "images/geographyLogo.png",
  },
  {
    id: 777,
    subject: "History",
    location: "Hendon",
    price: 10.0,
    space: 5,
    image: "images/historyLogo.png",
  },
  {
    id: 888,
    subject: "French",
    location: "Hendon",
    price: 10.0,
    space: 5,
    image: "images/frenchLogo.png",
  },
  {
    id: 999,
    subject: "IT",
    location: "Stratford",
    price: 10.0,
    space: 5,
    image: "images/computerLogo.png",
  },
  {
    id: 100,
    subject: "Spanish",
    location: "Ealing",
    price: 10.0,
    space: 5,
    image: "images/spanishLogo.png",
  },
];
